In [2]:
import pandas as pd

In [3]:
df = pd.read_csv(
    "./datasets/mymoviedb.csv",
    encoding="utf-8",
)
df.tail()

,Release_Date,Title,Overview,Popularity,Vote_Count,Vote_Average,Original_Language,Genre,Poster_Url
9822,1973-10-15,Badlands,A dramatization of the Starkweather-Fugate kil...,13.357,896.0,7.6,en,"Drama, Crime",https://image.tmdb.org/t/p/original/z81rBzHNgi...
9823,2020-10-01,Violent Delights,A female vampire falls in love with a man she ...,13.356,8.0,3.5,es,Horror,https://image.tmdb.org/t/p/original/4b6HY7rud6...
9824,2016-05-06,The Offering,When young and successful reporter Jamie finds...,13.355,94.0,5.0,en,"Mystery, Thriller, Horror",https://image.tmdb.org/t/p/original/h4uMM1wOhz...
9825,2021-03-31,The United States vs. Billie Holiday,Billie Holiday spent much of her career being ...,13.354,152.0,6.7,en,"Music, Drama, History",https://image.tmdb.org/t/p/original/vEzkxuE2sJ...
9826,1984-09-23,Threads,Documentary style account of a nuclear holocau...,13.354,186.0,7.8,en,"War, Drama, Science Fiction",https://image.tmdb.org/t/p/original/lBhU4U9Eeh...

In [4]:
df[(df["Vote_Average"] > 8.0)].head(20)

,Release_Date,Title,Overview,Popularity,Vote_Count,Vote_Average,Original_Language,Genre,Poster_Url
0,2021-12-15,Spider-Man: No Way Home,Peter Parker is unmasked and no longer able to...,5083.954,8940.0,8.3,en,"Action, Adventure, Science Fiction",https://image.tmdb.org/t/p/original/1g0dhYtq4i...
1,2022-03-01,The Batman,"In his second year of fighting crime, Batman u...",3827.658,1151.0,8.1,en,"Crime, Mystery, Thriller",https://image.tmdb.org/t/p/original/74xTEgt7R3...
20,2021-12-01,Sing 2,Buster and his new cast now have their sights ...,1112.900,2172.0,8.2,en,"Animation, Comedy, Family, Music",https://image.tmdb.org/t/p/original/aWeKITRFbb...
28,2020-10-16,Demon Slayer -Kimetsu no Yaiba- The Movie: Mug...,"Tanjirō Kamado, joined with Inosuke Hashibira,...",845.992,2224.0,8.4,ja,"Animation, Action, Adventure, Fantasy",https://image.tmdb.org/t/p/original/h8Rb9gBr48...
44,2022-03-10,Turning Red,Thirteen-year-old Mei is experiencing the awkw...,564.507,8.0,8.6,en,"Animation, Family, Comedy, Fantasy",https://image.tmdb.org/t/p/original/qsdjk9oAKS...
48,2021-10-15,Ron's Gone Wrong,"In a world where walking, talking, digitally c...",509.277,1000.0,8.1,en,"Animation, Science Fiction, Family, Comedy",https://image.tmdb.org/t/p/original/7M0uwPgwvP...
50,2021-05-26,Cruella,In 1970s London amidst the punk rock revolutio...,429.613,6675.0,8.2,en,"Comedy, Crime",https://image.tmdb.org/t/p/original/wToO8opxkG...
56,2021-03-18,Zack Snyder's Justice League,Determined to ensure Superman's ultimate sacri...,398.461,7414.0,8.3,en,"Action, Adventure, Fantasy, Science Fiction",https://image.tmdb.org/t/p/original/tnAuB8q5vv...
68,2021-11-04,Finch,"On a post-apocalyptic Earth, a robot, built to...",348.942,2075.0,8.1,en,"Science Fiction, Drama, Adventure",https://image.tmdb.org/t/p/original/jKuDyqx7jr...
71,2018-04-25,Avengers: Infinity War,As the Avengers and their allies have continue...,338.402,24079.0,8.3,en,"Adventure, Action, Science Fiction",https://image.tmdb.org/t/p/original/7WsyChQLEf...
125,2020-11-21,"Miraculous World: New York, United HeroeZ","During a school field trip, Ladybug and Cat No...",240.048,862.0,8.3,fr,"Animation, Family, Comedy, Adventure, TV Movie",https://image.tmdb.org/t/p/original/9YbyvcrHmY...
127,2019-12-20,My Hero Academia: Heroes Rising,Class 1-A visits Nabu Island where they finall...,239.599,890.0,8.4,ja,"Animation, Action, Fantasy, Adventure",https://image.tmdb.org/t/p/original/zGVbrulkup...
135,2016-10-07,Hacksaw Ridge,"WWII American Army Medic Desmond T. Doss, who ...",230.758,10667.0,8.2,en,"Drama, History, War",https://image.tmdb.org/t/p/original/fTuxNlgEm0...
161,2017-10-27,Coco,Despite his family’s baffling generations-old ...,210.527,15355.0,8.2,en,"Family, Animation, Fantasy, Music, Comedy, Adv...",https://image.tmdb.org/t/p/original/gGEsBPAijh...
171,2019-04-24,Avengers: Endgame,After the devastating events of Avengers: Infi...,205.308,20521.0,8.3,en,"Adventure, Science Fiction, Action",https://image.tmdb.org/t/p/original/or06FN3Dka...
178,2022-02-17,Dog,An army ranger and his dog embark on a road tr...,200.253,32.0,8.3,en,"Drama, Comedy",https://image.tmdb.org/t/p/original/pb8rHkAyoj...
183,2021-08-12,An Egg Rescue,Toto and his friends must rescue his egg child...,194.622,295.0,8.1,es,"Animation, Comedy",https://image.tmdb.org/t/p/original/ewrIYKTLaq...
185,2021-02-11,Pretty Guardian Sailor Moon Eternal The Movie ...,While under the care of the Outer Sailor Guard...,192.922,102.0,8.1,ja,"Animation, Action, Adventure, Comedy, Drama, F...",https://image.tmdb.org/t/p/original/f91rtk8dOD...
187,2021-11-24,Far From the Tree,"On an idyllic beach in the Pacific Northwest, ...",192.331,194.0,8.1,en,"Animation, Family",https://image.tmdb.org/t/p/original/39oaQUS0Kx...
191,2018-12-06,Spider-Man: Into the Spider-Verse,Miles Morales is juggling his life between bei...,190.775,10951.0,8.4,en,"Action, Adventure, Animation, Science Fiction",https://image.tmdb.org/t/p/original/iiZZdoQBEY...

In [5]:
df[(df["Vote_Average"] > 8.0) & (df["Genre"].str.contains("Drama, Crime"))].head(20)

,Release_Date,Title,Overview,Popularity,Vote_Count,Vote_Average,Original_Language,Genre,Poster_Url
609,1972-03-14,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",93.136,15614.0,8.7,en,"Drama, Crime",https://image.tmdb.org/t/p/original/eEslKSwcqm...
657,1994-09-23,The Shawshank Redemption,Framed in the 1940s for the double murder of h...,87.669,20911.0,8.7,en,"Drama, Crime",https://image.tmdb.org/t/p/original/q6y0Go1tsG...
731,1999-12-10,The Green Mile,A supernatural tale set on death row in a Sout...,81.142,13604.0,8.5,en,"Fantasy, Drama, Crime",https://image.tmdb.org/t/p/original/velWPhVMQe...
1007,1974-12-20,The Godfather: Part II,In the continuing saga of the Corleone crime f...,65.324,9393.0,8.6,en,"Drama, Crime",https://image.tmdb.org/t/p/original/hek3koDUyR...
1759,1990-09-12,GoodFellas,"The true story of Henry Hill, a half-Irish, ha...",44.572,9860.0,8.5,en,"Drama, Crime",https://image.tmdb.org/t/p/original/aKuFiU82s5...
2384,1984-05-23,Once Upon a Time in America,A former Prohibition-era Jewish gangster retur...,35.818,4053.0,8.4,en,"Drama, Crime",https://image.tmdb.org/t/p/original/i0enkzsL5d...
2784,2002-02-05,City of God,Buscapé was raised in a very violent environme...,31.944,5643.0,8.4,pt,"Drama, Crime",https://image.tmdb.org/t/p/original/k7eYdWvhYQ...
3260,1995-07-19,The Usual Suspects,"Held in an L.A. interrogation room, Verbal Kin...",28.399,8391.0,8.2,en,"Drama, Crime, Thriller",https://image.tmdb.org/t/p/original/bUPmtQzrRh...